server:
  forward-headers-strategy: framework
  port: 8080
spring:
  cache:
    cache-names: menuService
  datasource:
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 2
      pool-name: HikariDataSourcePool
    password: hrm
    url: jdbc:mysql://182.92.71.212:3306/hrm?useUnicode=true&characterEncoding=UTF-8
    username: hrm
  redis:
    port: 6379
    password: pa22w0rd
    host: 182.92.71.212
  mail:
    default-encoding: UTF-8
    host: smtp.mxhichina.com
    password: 1610940520qQ
    port: 25
    properties:
      mail:
        debug: false
        stmp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    protocol: smtp
    username: notice@0101.design

debug: false
# JavaMailSender 邮件发送的配置
#mybatis:
#  config-location: classpath:/mybatis-config.xml