server:
  port: 8080
spring:
  cache:
    cache-names: menuService
  datasource:
    password: hrm
    url: jdbc:mysql://127.0.0.1:3306/hrm?useUnicode=true&characterEncoding=UTF-8
    username: hrm
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #开启监控和防火墙
      filters: stat,wall
      #慢日志记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      #是否启用StatFilter默认值true
      web-stat-filter.enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: emm
        login-password: emm
        allow:
      #连接池初始化
      initial-size: 1
      min-idle: 1
      max-active: 20
      #初始化时的超时时间
      max-wait: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      max-evictable-idle-time-millis: 900000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      validation-query: select 1
      #spring监控
      aop-patterns: org.dev.hrm.service.*
      # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭 如果想用SQL防火墙 建议打开
      poolPreparedStatements: true
      #uri监控的过滤规则
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 5000

  redis:
    port: 6379
    password: pa22w0rd
    host: 127.0.0.1
  mail:
    default-encoding: UTF-8
    host: smtp.mxhichina.com
    password: 1610940520qQ
    port: 25
    properties:
      mail:
        debug: false
        stmp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    protocol: smtp
    username: notice@0101.design

debug: false
#mybatis:
#  config-location: classpath:/mybatis-config.xml