server:
  forward-headers-strategy: framework
  port: 80
spring:
  cache:
    cache-names: menuService
  datasource:
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 2
      pool-name: HikariDataSourcePool
    password: hrm
    url: jdbc:mysql://182.92.71.212:3306/hrm?useUnicode=true&characterEncoding=UTF-8
    username: hrm
  redis:
    port: 6379
    password: pa22w0rd
    host: 182.92.71.212
debug: false
#mybatis:
#  config-location: classpath:/mybatis-config.xml